name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and build the library
        run: |
          yarn
          yarn prepack
      - name: Run unit and integration tests
        run: yarn test
